module.exports = {
  roots: ['<rootDir>/src'],
  collectCoverageFrom: ['src/**/*.{ts,tsx}', '!src/**/*.d.ts'],
  setupFiles: ['react-app-polyfill/jsdom'],
  setupFilesAfterEnv: ['<rootDir>/config/jest/setupTests.ts'],
  testMatch: [
    '<rootDir>/src/**/__tests__/**/*.{ts,tsx}',
    '<rootDir>/src/**/*.{spec,test}.{ts,tsx}',
  ],
  testEnvironment: 'jest-environment-jsdom-fourteen',
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': '<rootDir>/node_modules/babel-jest',
    '^.+\\.css$': '<rootDir>/config/jest/cssTransform.js',
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '<rootDir>/config/jest/fileTransform.js',
  },
  transformIgnorePatterns: [
    '[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$',
    '^.+\\.module\\.(css|sass|scss)$',
  ],
  modulePaths: [],
  moduleNameMapper: {
    '^.+\\.module\\.(css|sass|scss)$': 'identity-obj-proxy',
    '^@client/constants(.*)$': '<rootDir>/src/constants$1',
    '^@client/dictionary(.*)$': '<rootDir>/src/dictionary$1',
    '^@client/models(.*)$': '<rootDir>/src/models$1',
    '^@client/repositories(.*)$': '<rootDir>/src/repositories$1',
    '^@client/services(.*)$': '<rootDir>/src/services$1',
    '^@client/stores(.*)$': '<rootDir>/src/stores$1',
    '^@client/styles(.*)$': '<rootDir>/src/styles$1',
    '^mst-types(.*)$': '<rootDir>/src/types/mst$1',
    '^@client/tcomb(.*)$': '<rootDir>/src/types/tcomb-types$1',
    '^@client/types(.*)$': '<rootDir>/src/types/typescript$1',
    '^@client/theme(.*)$': '<rootDir>/src/theme$1',
    '^@client/utils(.*)$': '<rootDir>/src/utils$1',
    '^mst-react-lite(.*)$': '<rootDir>/src/tools/mst-react-lite$1',
    '^mst-react-router-dom(.*)$': '<rootDir>/src/tools/mst-react-router-dom$1',
  },
  moduleFileExtensions: [
    'web.js',
    'js',
    'web.ts',
    'ts',
    'web.tsx',
    'tsx',
    'json',
    'web.jsx',
    'jsx',
    'node',
  ],
  watchPlugins: ['jest-watch-typeahead/filename', 'jest-watch-typeahead/testname'],
}
