import { INDENT_INITIAL_VALUE, BORDER_RADIUS_INITIAL_VALUE, MEDIA_QUERY_INITIAL_VALUE, BOX_SHADOWS_INITIAL_VALUE } from '@client/models'

export const THEME_STORE_INITIAL_VALUE = {
    INDENTS: INDENT_INITIAL_VALUE,
    BORDER_RADIUS: BORDER_RADIUS_INITIAL_VALUE,
    MEDIA_QUERY: MEDIA_QUERY_INITIAL_VALUE,
    BOX_SHADOWS: BOX_SHADOWS_INITIAL_VALUE,
}
