const MULTIPLIER_XS = 0.25
const MULTIPLIER_S = 0.5
const MULTIPLIER_M = 1
const MULTIPLIER_L = 2
const MULTIPLIER_XL = 3

export const SPACING_MULTIPLIER_XS = MULTIPLIER_XS
export const SPACING_MULTIPLIER_S = MULTIPLIER_S
export const SPACING_MULTIPLIER_M = MULTIPLIER_M
export const SPACING_MULTIPLIER_L = MULTIPLIER_L
export const SPACING_MULTIPLIER_XL = MULTIPLIER_XL
